### ISSUE TITLE
This seems like a bit too high of a number

### ISSUE THREAD

**Issue by CenTdemeern1** [DogeisCut/Combining-Cumulus#3]
https://github.com/DogeisCut/Combining-Cumulus/blob/760895754281133f94f28389173b059dc86472b7/src/cloud.gd#LL53C31-L53C39

(Loud sound warning)

https://github.com/DogeisCut/Combining-Cumulus/assets/24682280/7b2844f3-8997-4476-aa60-bfa135c42bdc

**Comment by DogeisCut** [comment]
I turned it that high for testing and forgot to turn it back
